### ISSUE TITLE
文档标题样式不生效

### ISSUE THREAD

**Issue by TCOTC** [frostime/siyuan-center-width#21]
![标题](https://github.com/frostime/siyuan-center-width/assets/78434827/e3e2d657-879e-4734-9bb2-8ee38381eda8)

**Comment by frostime** [comment]
我自己的机器测试的时候是正常的，不太确定你是怎么触发这种问题的。

![image](https://github.com/frostime/siyuan-center-width/assets/27268127/b6ba4370-46c2-4fbc-a571-b73633a0039f)

**Comment by TCOTC** [comment]
我新建工作空间试了一下，跟模式无关：

![插件](https://github.com/frostime/siyuan-center-width/assets/78434827/f5b3589f-40ad-4ecb-868a-27cc013739a4)

**Comment by frostime** [comment]
标题的偏移样式我是写了的，你打开开发者模式看一下有没有这个样式？

![image](https://github.com/frostime/siyuan-center-width/assets/27268127/b0e54670-6641-4a7d-8c67-81a65f70f87f)

**Comment by TCOTC** [comment]
确实没有

**Comment by TCOTC** [comment]
把

```css
#layouts div.layout__center div.protyle-content:not([data-fullwidth="true"])>div.protyle-title {
    margin-left: var(--lrwidth) !important;
    margin-right: var(--lrwidth) !important;
}
```

改成（去掉了 `>` ）

```css
#layouts div.layout__center div.protyle-content:not([data-fullwidth="true"]) div.protyle-title {
    margin-left: var(--lrwidth) !important;
    margin-right: var(--lrwidth) !important;
}
```

之后就可以了
